<?php

/**
 * Implements hook_menu().
 */
function araport_blast_menu(){
  $items = array();

  $items['apps/blast'] = array(
    'title' => 'Araport Blast+',
    'description' => 'Run Blast',
    'type' => MENU_CALLBACK,
    'page callback' => 'araport_blast_show',
    'access callback' => TRUE
  );

  return $items;
}

function araport_blast_show() {
  global $user;

  if ($user-> uid == 0) {
    $output = '<div class="jumbotron"><p>You need to be logged in to run Blast!</p><p>!login or !register</p></div>';

    return t($output, array(
      '!login' => l(t('Login'), 'user/login', array('query' => drupal_get_destination(), 'attributes' => array('class' => 'btn btn-primary'))),
      '!register' => l(t('Register for an account'), 'user/register', array('attributes' => array('class' => 'btn btn-default')))
    ));
  }

  $module_path = drupal_get_path('module', 'araport_blast');

  // app.css
  drupal_add_css($module_path . '/araport-blast-app/app/styles/app.css', 'file');

  // filesaver.js
  drupal_add_js($module_path . '/araport-blast-app/bower_components/FileSaver.js/FileSaver.min.js', array('type' => 'file', 'preprocess' => FALSE));

  // app.js
  drupal_add_js($module_path . '/araport-blast-app/app/scripts/app.js', array('type' => 'file', 'scope' => 'footer', 'preprocess' => FALSE));

  return file_get_contents($module_path . '/araport-blast-app/app/app.html');
}
